### ISSUE TITLE
Include onboarding app

### ISSUE THREAD

**Issue by ACertainTopfi** [sodaliterocks/sodalite#19]
Pantheon can be customized using https://github.com/elementary/onboarding after the initial setup. This is something we should consider adding to Sodalite. It has already been ported to .rpm and is utilized in the OpenSuse related GeckoLinux: https://build.opensuse.org/package/show/X11:Pantheon/elementary-onboarding

**Comment by electricduck** [comment]
This app did spring to mind the other, however, we'd need to maintain a build ourselves as I feel the app is a little problematic in its current state:

1. It mentions "elementary OS" and "elementary, Inc." a lot.
2. It mentions AppCenter which we currently don't ship with (instead using GNOME Software).
3. The Housekeeping section is something Fedora has yet to ship with (this is configurable via Switchboard and runs via the settings daemon).

I'm actually more inclined to write our own, as we could also mention the `rpm-ostree` system and how updates work. It seems a relatively simple app and I have dabbled with Vala myself.

**Comment by amz-x** [comment]
Not sure if this helps, however, I maintain the following package - https://src.fedoraproject.org/rpms/elementary-onboarding

**Comment by electricduck** [comment]
Awesome stuff, @amz-x ! I gave this app a spin (on the `devel` branch which uses F36) and although it works, I have met a few niggles.

### The Bad

#### Welcome view

![image](https://user-images.githubusercontent.com/1594644/169113972-41329899-c7df-477b-8c80-4c2c61d824a6.png)

This is the only view that had problems:
* Logo is missing
  * This is set with `LOGO` in `os-release`, which we provide, so not yet sure why its not showing up (since it does in **System Settings ➔ System ➔ Operating System**).
* **Basics Guide...** goes to [Learning The Basics on elementary.io](https://elementary.io/docs/learning-the-basics).
  * This is set with `DOCUMENTATION_URL` in `os-release`, which we don't yet provide.
* **Get Involved...** goes to [Get Involved on elementary.io](https://elementary.io/get-involved).
  * **[This is hardcoded!](https://github.com/elementary/onboarding/blob/master/src/Views/WelcomeView.vala#L41-L45)**

### The Good

 * **Get Some Apps** & **Automatic Updates** views do not appear. We do not ship **AppCenter**, and Onboarding [checks for the existance of it](https://github.com/elementary/onboarding/blob/master/src/MainWindow.vala#L87-L97), so it correctly doesn't show either of these views.
 * **Early Access** view could be triggered by us for builds from the `devel` branch, as this is done by having by `Early Access` being in `VERSION` in `os-release`. This is more of a "nice to have" than anything.
 * **Choose Your Look**, **Night Light**, **Housekeeping**, **Online Accounts**, and **Ready to Go**, all function correctly.
 * After finishing up, Onboarding will never display again, even when manually opening it with `io.elementary.onboarding`.
   * This occurs from the appropriate values being set by `io/elementary/onboarding/viewed` in `dconf`.

**Comment by electricduck** [comment]
Completed with d4da21c66ed40b0ac516c94bd4fa6ff7944bbe0f and a78c63474b94a4aea7ee3da8b3c072601a5b4092
