### ISSUE TITLE
Touchpad gesture to switch workspaces are laggy

### ISSUE THREAD

**Issue by MrGreenTea** [sodaliterocks/sodalite#23]
Thanks for the great work, really glad that this works so well!

When swiping three fingers up there is a small jank and then the multitasking view animation starts.
When swiping left and right a similar thing happens and looks like this, with the blue rectangle animating with the motion.

![image](https://user-images.githubusercontent.com/9407731/151426860-df3ccf61-f587-4089-ad75-4b7356173d62.png)

**Comment by MrGreenTea** [comment]
To me it looks like some part of gnome is trying to react to the gesture too.

**Comment by MrGreenTea** [comment]
![image](https://user-images.githubusercontent.com/9407731/151427260-9a451664-ff47-4388-b739-c7e54d2f7ff1.png)

**Comment by electricduck** [comment]
Hm, I cannot seem to replicate this, on even one of my fairly underpowered laptops.

What GPU do you have on that machine, might I ask?

> To me it looks like some part of gnome is trying to react to the gesture too.

Also, can you elaborate on this? If you're talking about the blue boxes, this is supposed to happen, and also occurs in elementaryOS.

**Comment by MrGreenTea** [comment]
> > To me it looks like some part of gnome is trying to react to the gesture too.
> 
> Also, can you elaborate on this? If you're talking about the blue boxes, this is supposed to happen, and also occurs in elementaryOS.

On my eOS install i've never seen these blue boxes. Also when finishing the gesture the open window is tiled to one half of the screen, like so:

![image](https://user-images.githubusercontent.com/9407731/151514894-05eb098e-7205-45e1-a74c-4db2a12c5d78.png)


I am using my Thinkpad P53:
![image](https://user-images.githubusercontent.com/9407731/151514979-7a80414d-37b6-43df-ba63-e38b1f57a275.png)


On my eOS install this has not been an issue on that same machine.

I'd be glad to assist with further info/feedback and am comfortable with deeper debugging, if that could be of any help :)

**Comment by electricduck** [comment]
### Touchpad issues

> On my eOS install i've never seen these blue boxes.

My mistake, I'm misremembering them. Yes, you are correct. I've since tracked this down to be an error in the TouchEgg config (the default one is causing problems, so I've just taken the one from elementaryOS). Currently in the progress of testing this on my own laptop (with the commit b0c88f7).

As for you now, you should just be-able to replace the contents of `~/.config/touchegg/touchegg.conf` with:

```
<touchégg>
  <settings>
    <property name="animation_delay">150</property>
    <property name="action_execute_threshold">20</property>
    <property name="color">auto</property>
    <property name="borderColor">auto</property>
  </settings>
  <application name="All">
  </application>
</touchégg>
```

You can either restart the service (`sudo systemctl restart touchegg`) or reboot the system.

---

### GPU issues (maybe?)

> When swiping three fingers up there is a small jank and then the multitasking view animation starts.

As for this issue, I noticed one of your GPUs is an Nvidia GPU. Dual GPUs are still not quite there yet in Linux, but its likely because you're using the Nouvea driver, which is the open-source implementation of Nvidia's driver, which doesn't work very well. Sodalite does not yet provide the official proprietary GPU driver (as I'm in the progress of coming up with the best way to do it), but you can install the driver using the [instructions from RPMFusion](https://rpmfusion.org/Howto/NVIDIA).

In short, these are the commands you need to invoke to install the Nvidia drivers from RPMFusion:

```
# Install RPMFusion repository
sudo rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
# Install Nvidia drivers
sudo rpm-ostree install akmod-nvidia xorg-x11-drv-nvidia-cuda #optional if using nvidia-smi or cuda
# Apply the kernel args to make it work
sudo rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1
# Reboot!
sudo shutdown -r now
```

I can verify this works on an Nvidia system as my own tower uses one. However, your mileage may vary for a dual-GPU system like your own.
