### ISSUE TITLE
Fedora 36-based image is unusable

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/sodalite#28]
Rebasing to `sodalite/f36/x86_64/base` to version `36-22.8` (based on Fedora 36) leads to a whole range of problems, rendering the desktop entirely unusable, as shown in the below photos (which speak for themselves).

### Login screen (LightDM)

![IMG20220329161912](https://user-images.githubusercontent.com/1594644/160649228-a4433054-638c-41b1-861e-70b621c194a0.jpg)

### Desktop

![IMG20220329162039](https://user-images.githubusercontent.com/1594644/160649235-076c88f2-d39a-4844-bd90-ab5ee0f1c413.jpg)

### Open applications

![IMG20220329162121](https://user-images.githubusercontent.com/1594644/160649240-5698b964-9ef2-49b4-900f-0aee18815636.jpg)

<hr />

It's worth mentioning Fedora Linux 36 is still in beta, and is not due for a stable release until&mdash;at the earliest&mdash;[19-Apr-2022](https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html), so it might be a case of it just fixing itself by the time that comes around. The `stable` verison of Sodalite is still on 35, and we will only bump it to 36 when any major issues are fixed.

Having on briefly played around with this verison, I am not immediately sure of what the problem is, and I cannot find any related issues on other issue trackers (such as RedHat Bugzilla). Wondering if @decathorpe could shed any light?

**Comment by decathorpe** [comment]
The problems you're seeing (the "Oh no!" screen, missing wallpaper, rendering issues of dock and wingpanel) are caused by a crashed `gala` compositor, which in turn was caused by ABI / API changes between mutter 42.alpha and 42.beta.

However, this issue was known to me, and should have been resolved with the latest update for `gala` (bump from version 6.2.1 to 6.3.0 plus some upstream patches to support mutter versions 42.beta and newer), so it looks like the image you're using hasn't been rebuilt since that update has been pushed to stable three days ago.

c.f. https://bodhi.fedoraproject.org/updates/FEDORA-2022-85614f3154

**Comment by electricduck** [comment]
Recently tested a build and this is now resolved. Seems the first time I did the build was literally a few hours before 6.3.0 went live!
