### ISSUE TITLE
cant login after rebase

### ISSUE THREAD

**Issue by TopRoupi** [sodaliterocks/sodalite#37]
im "getting unable to login starting session failed returned error code 1" while trying to login
also if i set my password wrong it will just froze and i need to restart

lightdm log:
[lightdm.log](https://github.com/sodaliterocks/sodalite/files/9097422/lightdm.log)

also tried creating a second user but it does not show in the lightdm login only on gnome.
found other people getting the same error but in my case i dont have a .Xauthority file in my home dir.

**Comment by electricduck** [comment]
Just so I get some more background on this:
 * Is this the first time you're rebased to Sodalite (i.e. rebasing from Fedora Silverblue to Sodeliad), or is it from an update?
 * What is the output of `rpm-ostree status`?
 * What is the output of `cat /usr/lib/sodalite-buildinfo`?

Thanks :smile:

**Comment by TopRoupi** [comment]
it is the first time i rebased to sodalite, my system was originally fedora silverblue 34.
i did the rebase from fedora 36 to sodalite base

![image](https://user-images.githubusercontent.com/38011914/178721404-7eacbb71-c664-4864-95cc-8219aa2aea26.png)

![image](https://user-images.githubusercontent.com/38011914/178727136-01264410-2321-4d8b-917c-bbec740a987d.png)

**Comment by electricduck** [comment]
Try as a might, I've so far been unable to replicate this on a fresh install of Sodalite (36-22.11.5). Is there anything else you did before rebasing to Sodalite that you think might be of help?

Looking through your log, there is `[+113.75s] CRITICAL: session_real_run: assertion 'priv->argv != NULL' failed` (which isn't much help in itself), but I'm unable to find any other issues relating to this apart from some incredibly old reports for Greeter that were long-ago fixed in the upstream,

**Comment by TopRoupi** [comment]
well i tried to change a bunch on configs with no success, also tried to remove all the layer packages.
only way i could login in elementary was with startx gnome-session --session=pantheon, but all the animations was bugged and plank didnt worked.

i can give sodalite a try again if i do a fresh install of silverblue.
