### ISSUE TITLE
Deepin variant

### ISSUE THREAD

**Issue by pieckenst** [sodaliterocks/sodalite#65]
It would be a nice to have thing, considering fedora server allows you to install it out of the box during software selection
So having it be an option in fedora silverblue base would be a nice to have

**Comment by electricduck** [comment]
As you may have spotted, there is an experimental GNOME version of Sodalite buried in the code, there as a backup in case Pantheon just wasn't viable in the future. Because the codebase is designed to accommodate such a thing, it would be fairly feasible for Deepin to be added. However,

* I didn't want Sodalite to have loads of desktop versions
* I have never used Deepin so I'm not aware of what could potentially not be quite correct on Fedora

But on the flipside there doesn't seem to be a Deepin version of Fedora Silverblue, so I suppose it would be nice for Sodalite to showcase the two most beautiful desktops around 😄.

**Comment by pieckenst** [comment]
as for package list this https://fedoraproject.org/wiki/SIGs/DeepinDE page seems to list all the things in the fedora repositories

**Comment by electricduck** [comment]
Deepin is successfully being built on the build server now and can be pulled from the `sodalite/devel/x86_64/desktop-deepin` branch. Note its only available on the `devel` channel &mdash; **do not use on production systems**. The Deepin variant is still in its very early stages, and although works, has lots of broken quirks as well as a myriad of missing stock applications.
