### ISSUE TITLE
GNOME Software broken

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/sodalite#81]
At some point, Software seems to have entirely stopped working correctly

**Explore** is empty and doesn't load anything

![image](https://user-images.githubusercontent.com/1594644/225212898-1a62c050-4928-4f50-82b2-a5a0b1402389.png)

**Search** is unable to find anything

![image](https://user-images.githubusercontent.com/1594644/225212984-5b54dd11-600a-4741-be18-d06a2c019f37.png)

**Updates** throws errors

![image](https://user-images.githubusercontent.com/1594644/225212860-50da9ca3-15a1-456e-9b58-9e95a3c8120a.png)

**Comment by electricduck** [comment]
Seems to be an upstream issue. Related issues:
 * https://github.com/fedora-silverblue/issue-tracker/issues/327
 * https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1793

**Comment by team-cons** [comment]
Very random question, and i hope not in the wrong place, but has it been considered to have the elementary software center thingy instead ? I suppose it is not there because theres no backend for layering rpms ?

for users only interested in installing flatpaks with a GUI frontend and no GUI for layering, would there be a way to replace the gnome one with the elementary one ? That may even be an elegant workaround until upstream figure that shit out.

**Comment by electricduck** [comment]
> Very random question, and i hope not in the wrong place, but has it been considered to have the elementary software center thingy instead ? I suppose it is not there because theres no backend for layering rpms ?

AppCenter has no support for rpm-ostree at all. Attempting to launch it just throws a load of errors. Unless we fork it and do a major amount of work, there's simply no way it can be bodged for it to work

**Comment by electricduck** [comment]
Sodalite 4 is near EoL soon, and Software works on 5+. Closing issue.
